CREATE TABLE IF NOT EXISTS submissions(
	id INTEGER AUTO_INCREMENT NOT NULL ,
	address_1 TEXT,
	address_2 TEXT,
	city TEXT,
	state TEXT,
	country TEXT,
	zipcode INTEGER,
	paragraph TEXT,
	site TEXT,
	exec_coaching TEXT NOT NULL ,
	team_develop TEXT NOT NULL ,
	more_other TEXT NOT NULL ,
	c_suite TEXT NOT NULL ,
	hr_rep TEXT NOT NULL ,
	position TEXT NOT NULL ,
	company_name TEXT,
	company_size TEXT,
	phone TEXT NOT NULL ,
	email TEXT NOT NULL ,
	first_name TEXT NOT NULL ,
	last_name TEXT NOT NULL ,
	title TEXT NOT NULL ,
	stamp TEXT NOT NULL ,
	PRIMARY KEY ( id )
);